# framework:
#     messenger:
#         failure_transport: failed

#         transports:
#             # https://symfony.com/doc/current/messenger.html#transport-configuration
#             async:
#                 dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                 options:
#                     use_notify: true
#                     check_delayed_interval: 60000
#                 retry_strategy:
#                     max_retries: 3
#                     multiplier: 2
#             failed: 'doctrine://default?queue_name=failed'
#             # sync: 'sync://'

#         routing:
#             Symfony\Component\Mailer\Messenger\SendEmailMessage: async
#             Symfony\Component\Notifier\Message\ChatMessage: async
#             Symfony\Component\Notifier\Message\SmsMessage: async
#             App\Service\MessageService: amqp_message_Service


            # Route your messages to the transports
            # 'App\Message\YourMessage': async
# config/packages/messenger.yaml

# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            amqp:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: news
                        type: fanout
                    queues:
                        news: ~
        routing:
            'App\MessageHandler\MessageServiceHandler': amqp
            # config/packages/messenger.yaml


